<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Opengento\WebapiLogger\ViewModel\Detail $viewModel */

$viewModel = $block->getData('viewModel');
$log = $viewModel->getLog();
?>
<h1><?= $escaper->escapeHtml(__('Log id: %1', $log->getData('log_id'))) ?></h1>
<br/>
<h1><?= $escaper->escapeHtml(__('Request')) ?></h1>
<p><b><?= $escaper->escapeHtml(__('requestor_ip:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('requestor_ip')) ?></p>
<br/>
<p><b><?= $escaper->escapeHtml(__('request_url:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('request_url')) ?></p>
<br/>
<p><b><?= $escaper->escapeHtml(__('request_method:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('request_method')) ?></p>
<br/>
<?php if (preg_match('/^<\?xml/', $log->getData('request_body'))): ?>
    <p><b><?= $escaper->escapeHtml(__('request_body:')) ?></b></p>
    <pre style="border:1px solid #CCC;height:300px;overflow-y:auto;padding:10px;font-size:12px"><?= $escaper->escapeHtml($log->getData('request_body')) ?></pre>
<?php else: ?>
    <p><b><?= $escaper->escapeHtml(__('request_body:')) ?></b> <button class="js_beauty_json"><?= $escaper->escapeHtml(__('Prettify JSON')) ?></button></p>
    <p><?= $escaper->escapeHtml($log->getData('request_body')) ?></p>
<?php endif; ?>
<br/>
<p><b><?= $escaper->escapeHtml(__('request_headers:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('request_headers')) ?></p>
<br/>
<h1><?= $escaper->escapeHtml(__('Response')) ?></h1>
<p><b><?= $escaper->escapeHtml(__('response_code:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('response_code')) ?></p>
<br/>
<?php if (preg_match('/^<\?xml/', $log->getData('response_body'))): ?>
    <p><b><?= $escaper->escapeHtml(__('response_body:')) ?></b></p>
    <pre style="border:1px solid #CCC;height:300px;overflow-y:auto;padding:10px;font-size:12px"><?= $log->getData('response_body') ?></pre>
<?php else: ?>
    <p><b><?= $escaper->escapeHtml(__('response_body:')) ?></b> <button class="js_beauty_json">Prettify JSON')) ?></button></p>
    <p><?= $escaper->escapeHtml($log->getData('response_body')) ?></p>
<?php endif; ?>
<br/>
<p><b><?= $escaper->escapeHtml(__('request_datetime:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('request_datetime')) ?></p>
<br/>
<p><b><?= $escaper->escapeHtml(__('response_datetime:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('response_datetime')) ?></p>
<br/>
<p><b><?= $escaper->escapeHtml(__('created_at:')) ?></b></p>
<p><?= $escaper->escapeHtml($log->getData('created_at')) ?></p>
<br/>

<script>
    require([
        'jquery',
        'Opengento_WebapiLogger/js/js-beautify/beautify.min'
    ], function (
        $,
        beautify
    ) {
        'use strict';

        $('.js_beauty_json').click(function (e) {
            let $button = $(e.target),
                $target = $button.parent().next(),
                value = $target.text();

            value = beautify.js_beautify(value, {
                "indent_size": 4,
                "indent_char": "&nbsp;",
                "indent_with_tabs": false,
                "editorconfig": false,
                "eol": "<br/>",
                "end_with_newline": false,
                "indent_level": 0,
                "preserve_newlines": true,
                "max_preserve_newlines": 10,
                "space_in_paren": false,
                "space_in_empty_paren": false,
                "jslint_happy": false,
                "space_after_anon_function": false,
                "space_after_named_function": false,
                "brace_style": "collapse",
                "unindent_chained_methods": false,
                "break_chained_methods": false,
                "keep_array_indentation": false,
                "unescape_strings": false,
                "wrap_line_length": 0,
                "e4x": false,
                "comma_first": false,
                "operator_position": "before-newline",
                "indent_empty_lines": false,
                "templating": ["auto"]
            });

            $target.html(value);
            $button.hide();
        })
    });
</script>
